export const REQUEST_STORE_PENDING = 'REQUEST_STORE_PENDING';
export const REQUEST_STORE_SUCCESS = 'REQUEST_STORE_SUCCESS';
export const REQUEST_STORE_FAILURE = 'REQUEST_STORE_FAILURE';

export const REQUEST_PICTURE_PENDING = 'REQUEST_PICTURE_PENDING';
export const REQUEST_PICTURE_SUCCESS = 'REQUEST_PICTURE_SUCCESS';
export const REQUEST_PICTURE_FAILURE = 'REQUEST_PICTURE_FAILURE';
