export const REQUEST_STORE_PENDING = 'REQUEST_STORE_PENDING';
export const REQUEST_STORE_SUCCESS = 'REQUEST_STORE_SUCCESS';
export const REQUEST_STORE_FAILURE = 'REQUEST_STORE_FAILURE';

export const REQUEST_STATUS_PENDING = 'REQUEST_STATUS_PENDING';
export const REQUEST_STATUS_SUCCESS = 'REQUEST_STATUS_SUCCESS';
export const REQUEST_STATUS_FAILURE = 'REQUEST_STATUS_FAILURE';

export const REQUEST_REVIEWS_PENDING = 'REQUEST_REVIEWS_PENDING';
export const REQUEST_REVIEWS_SUCCESS = 'REQUEST_REVIEWS_SUCCESS';
export const REQUEST_REVIEWS_FAILURE = 'REQUEST_REVIEWS_FAILURE';

export const REQUEST_ABOUT_PENDING = 'REQUEST_ABOUT_PENDING';
export const REQUEST_ABOUT_SUCCESS = 'REQUEST_ABOUT_SUCCESS';
export const REQUEST_ABOUT_FAILURE = 'REQUEST_ABOUT_FAILURE';
